DROP TABLE IF EXISTS Dictionary;

CREATE TABLE Dictionary
( word  VARCHAR(8) NOT NULL
, meaning  VARCHAR(4096) NOT NULL
, PRIMARY KEY (word)
);

DROP TABLE IF EXISTS Word5;

CREATE TABLE Word5
( word  VARCHAR(5) NOT NULL
, status INTEGER NOT NULL
, PRIMARY KEY (word)
);

DROP TABLE IF EXISTS Word6;

CREATE TABLE Word6
( word  VARCHAR(6) NOT NULL
, status INTEGER NOT NULL
, PRIMARY KEY (word)
);

DROP TABLE IF EXISTS Word7;

CREATE TABLE Word7
( word  VARCHAR(7) NOT NULL
, status INTEGER NOT NULL
, PRIMARY KEY (word)
);

DROP TABLE IF EXISTS Word8;

CREATE TABLE Word8
( word  VARCHAR(8) NOT NULL
, status INTEGER NOT NULL
, PRIMARY KEY (word)
);

