no = 0
x = {}
x[no]= ['Charity Auction!', 'Headline', 'The Black Goat of the Woods', "Hibb's Roadhouse"]
no += 1
x[no]= ['Checkered Cab Trials Begin!', 'Headline', 'The Black Goat of the Woods', 'The Witch House']
no += 1
x[no]= ['Construction Crew Conundrum!', 'Headline', 'The Black Goat of the Woods', 'Graveyard']
no += 1
x[no]= ['Endlessly Breeding', 'Rumor', 'The Black Goat of the Woods', '', 'Two doom tokens']
no += 1
x[no]= ['Fires in the Night', 'Environment (Mystic)', 'The Black Goat of the Woods', 'Independence Square', 'Gate burst']
no += 1
x[no]= ['Full Moon', 'Environment (Weather)', 'The Black Goat of the Woods', 'Graveyard', 'Gate burst']
no += 1
x[no]= ['Funnel Clouds', 'Environment (Weather)', 'The Black Goat of the Woods', 'Historical Society']
no += 1
x[no]= ['Gypsy Caravan', 'Environment (Urban)', 'The Black Goat of the Woods', 'The Unnamable']
no += 1
x[no]= ['Horns of the Black Goat', 'Environment (Mystic)', 'The Black Goat of the Woods', 'Unvisited Isle', 'Gate burst']
no += 1
x[no]= ['Lightning Strikes Twice!', 'Headline', 'The Black Goat of the Woods', 'Unvisited Isle']
no += 1
x[no]= ['Mysterious Crates Found Empty!', 'Headline', 'The Black Goat of the Woods', 'Woods']
no += 1
x[no]= ['One Thousand Young', 'Rumor', 'The Black Goat of the Woods', '', 'Two doom tokens']
no += 1
x[no]= ['Parazoologist Visits Miskatonic U.', 'Environment (Urban)', 'The Black Goat of the Woods', 'Woods', 'Gate burst']
no += 1
x[no]= ['Pets and Wildlife Mutilated!', 'Headline', 'The Black Goat of the Woods', 'Black Cave', 'Gate burst']
no += 1
x[no]= ['Rash of Missing Persons!', 'Headline', 'The Black Goat of the Woods', 'Independence Square']
no += 1
x[no]= ['Rituals of Power', 'Environment (Mystic)', 'The Black Goat of the Woods', 'Black Cave']
no += 1
x[no]= ['Strange Sightings! (3)', 'Headline', 'The Black Goat of the Woods', '', 'Monster surge']
no += 1
x[no]= ['Strange Sightings! (4) x2', 'Headline', 'The Black Goat of the Woods', '', 'Monster surge']
no += 1
x[no]= ['Strange Whispers Promise Vengeance!', 'Headline', 'The Black Goat of the Woods', 'Science Building']
no += 1
x[no]= ['Superstitions Abound!', 'Headline', 'The Black Goat of the Woods', 'The Unnamable', 'Gate burst']
no += 1
x[no]= ['Tongue-Tied Teacher Taunted!', 'Headline', 'The Black Goat of the Woods', 'Silver Twilight Lodge']
no += 1
x[no]= ['Vivisection Victim!', 'Headline', 'The Black Goat of the Woods', 'The Witch House', 'Gate burst']
no += 1

i = 0
while i < no:
  y = x[i]
  print "'%s', %s, '%s'" % (y[0], y[1].upper(),y[3].upper().replace("'",'').replace(' ',''))
  i += 1